# **Funções de Indexação**

In [1]:
import numpy as np

## np.nonzero

In [2]:
array = np.array([
    [1, 0, 0],
    [0, 2, 0],
    [3, 4, 0]
])

In [3]:
indices = np.nonzero(array)
indices

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [4]:
array[indices]

array([1, 2, 3, 4])

## np.where

In [5]:
array_1d = np.arange(10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.where(array_1d < 4)

(array([0, 1, 2, 3]),)

In [7]:
np.where(array_1d < 4, 0, 1)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [8]:
np.where(array_1d < 4, array_1d, array_1d + 10)

array([ 0,  1,  2,  3, 14, 15, 16, 17, 18, 19])

In [9]:
other_array_1d = np.arange(50, 60)
other_array_1d

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [10]:
np.where(array_1d < 4, array_1d, other_array_1d)

array([ 0,  1,  2,  3, 54, 55, 56, 57, 58, 59])

In [11]:
array_2d = np.arange(0, 20).reshape(4, 5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
np.where(array_2d % 2 == 0, array_2d, -1)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1],
       [10, -1, 12, -1, 14],
       [-1, 16, -1, 18, -1]])

## np.argwhere

In [13]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
np.argwhere(array_2d % 2 ==0)

array([[0, 0],
       [0, 2],
       [0, 4],
       [1, 1],
       [1, 3],
       [2, 0],
       [2, 2],
       [2, 4],
       [3, 1],
       [3, 3]])

## np.selectc

In [15]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.select(
    condlist=[array_1d < 4, array_1d > 7],
    choicelist=[array_1d + 10, array_1d + 20],
    default=-1
)

array([10, 11, 12, 13, -1, -1, -1, -1, 28, 29])

## np.unravel_index

In [17]:
shape = (4, 5)
array = np.arange(20).reshape(shape)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
np.unravel_index(indices=12, shape=shape)

(np.int64(2), np.int64(2))

## np.diag_indices

In [19]:
indices = np.diag_indices(n=3, ndim=2)
indices

(array([0, 1, 2]), array([0, 1, 2]))

In [20]:
array = np.arange(0, 9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
array[indices] = -1
array

array([[-1,  1,  2],
       [ 3, -1,  5],
       [ 6,  7, -1]])

## np.tril_indices

## np.triu_indices

## np.diag_indices_from, np.tril_indices_from e np.triu_indices_from