# **Arrays Preenchidos**

In [1]:
import numpy as np

## np.zeros

In [2]:
np.zeros(shape=3)

array([0., 0., 0.])

In [3]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros(shape=(2,3)).dtype

dtype('float64')

## np.ones

In [5]:
np.ones(shape=2)

array([1., 1.])

In [6]:
np.ones(shape=(3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## np.full

In [7]:
np.full(shape=(2, 3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4]])

In [ ]:
array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array.shape

(2, 3)

In [11]:
np.zeros_like(a=array)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
np.ones_like(a=array)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
np.full_like(a=array, fill_value=5)

array([[5, 5, 5],
       [5, 5, 5]])

## np.empty

In [14]:
np.empty(shape=(2,3))

array([[3.47739925e-081, 3.80364451e+175, 2.67969078e-032],
       [1.22523826e-046, 2.12774504e-052, 1.11262266e-307]])

## np.eye

In [15]:
np.eye(N=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(N=5, M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

## np.identity

In [17]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## np.arange

In [18]:
np.arange(stop=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(start= 3,stop=10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(start= 3,stop=10, step=3)

array([3, 6, 9])

In [22]:
np.arange(start=10, stop=3, step=-2)

array([10,  8,  6,  4])

In [23]:
np.arange(start=1, stop=3, step=0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75])

## np.linspace

In [24]:
np.linspace(start=1, stop=10, num=4)

array([ 1.,  4.,  7., 10.])

In [25]:
np.linspace(start=1, stop=10, num=7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

## np.logspace

In [26]:
np.logspace(start=1, stop=4, num=4)

array([   10.,   100.,  1000., 10000.])

## np.geomspace

In [27]:
np.geomspace(start=10, stop=10_000, num=4)

array([   10.,   100.,  1000., 10000.])

In [28]:
np.geomspace(start=10, stop=10000, num=4)

array([   10.,   100.,  1000., 10000.])