# **Álgebra Linear**

In [1]:
import numpy as np

## Produto matriciais e vetores

In [2]:
rng = np.random.default_rng(seed=2)

In [3]:
vector_1 = rng.integers(low=-10, high=10, size=4)
vector_1

array([ 6, -5, -8, -5])

In [4]:
vector_2 = rng.integers(low=-10, high=10, size=4)
vector_2

array([-2,  6, -1, -9])

In [5]:
matrix_1 = rng.integers(low=-10, high=10, size=(4, 3))
matrix_1

array([[-4,  2,  6],
       [ 4,  9, -7],
       [ 7, -9,  1],
       [-5, -6,  3]])

In [7]:
matrix_2 = rng.integers(low=-10, high=10, size=(3, 4))
matrix_2

array([[  8,   9,   7,   3],
       [ -3,  -3, -10,  -7],
       [ -4,  -4,   1,   0]])

In [8]:
matrix_3 = rng.integers(low=-10, high=10, size=(4, 3))
matrix_3

array([[ 3,  7,  7],
       [ 5,  9, -4],
       [ 8,  8, -6],
       [-1,  1,  3]])

In [9]:
matrix_4 = rng.integers(low=-10, high=10, size=(3, 3))
matrix_4

array([[ 4, -8, -1],
       [-8,  9, -6],
       [-2,  7,  0]])

## np.dot

In [10]:
vector_1, vector_2

(array([ 6, -5, -8, -5]), array([-2,  6, -1, -9]))

In [11]:
np.dot(a=vector_1, b=vector_2)

np.int64(11)

In [12]:
matrix_1, matrix_2

(array([[-4,  2,  6],
        [ 4,  9, -7],
        [ 7, -9,  1],
        [-5, -6,  3]]),
 array([[  8,   9,   7,   3],
        [ -3,  -3, -10,  -7],
        [ -4,  -4,   1,   0]]))

In [13]:
np.dot(a=matrix_1, b=matrix_2)

array([[-62, -66, -42, -26],
       [ 33,  37, -69, -51],
       [ 79,  86, 140,  84],
       [-34, -39,  28,  27]])

In [14]:
matrix_2, vector_1

(array([[  8,   9,   7,   3],
        [ -3,  -3, -10,  -7],
        [ -4,  -4,   1,   0]]),
 array([ 6, -5, -8, -5]))

In [15]:
np.dot(matrix_2, vector_1)

array([-68, 112, -12])

## np.vdot

In [16]:
np.vdot(vector_1, vector_2)

np.int64(11)

## np.inner

In [17]:
np.inner(vector_1, vector_2)

np.int64(11)

In [18]:
np.inner(matrix_1, matrix_3)

array([[  44,  -26,  -52,   24],
       [  26,  129,  146,  -16],
       [ -35,  -50,  -22,  -13],
       [ -36,  -91, -106,    8]])

## np.outer

## np.matmul

## np.linalg.det