# **Álgebra Linear**

In [1]:
import numpy as np

## Produto matriciais e vetores

In [2]:
rng = np.random.default_rng(seed=2)

In [3]:
vector_1 = rng.integers(low=-10, high=10, size=4)
vector_1

array([ 6, -5, -8, -5])

In [4]:
vector_2 = rng.integers(low=-10, high=10, size=4)
vector_2

array([-2,  6, -1, -9])

In [5]:
matrix_1 = rng.integers(low=-10, high=10, size=(4, 3))
matrix_1

array([[-4,  2,  6],
       [ 4,  9, -7],
       [ 7, -9,  1],
       [-5, -6,  3]])

In [6]:
matrix_2 = rng.integers(low=-10, high=10, size=(3, 4))
matrix_2

array([[-4,  1, -5, -7],
       [ 4, -2,  3,  3],
       [ 8, -2, -6,  2]])

In [7]:
matrix_3 = rng.integers(low=-10, high=10, size=(4, 3))
matrix_3

array([[  8,   9,   7],
       [  3,  -3,  -3],
       [-10,  -7,  -4],
       [ -4,   1,   0]])

In [8]:
matrix_4 = rng.integers(low=-10, high=10, size=(3, 3))
matrix_4

array([[ 3,  7,  7],
       [ 5,  9, -4],
       [ 8,  8, -6]])

## np.dot

In [9]:
vector_1, vector_2

(array([ 6, -5, -8, -5]), array([-2,  6, -1, -9]))

In [10]:
np.dot(a=vector_1, b=vector_2)

np.int64(11)

In [11]:
matrix_1, matrix_2

(array([[-4,  2,  6],
        [ 4,  9, -7],
        [ 7, -9,  1],
        [-5, -6,  3]]),
 array([[-4,  1, -5, -7],
        [ 4, -2,  3,  3],
        [ 8, -2, -6,  2]]))

In [12]:
np.dot(a=matrix_1, b=matrix_2)

array([[ 72, -20, -10,  46],
       [-36,   0,  49, -15],
       [-56,  23, -68, -74],
       [ 20,   1, -11,  23]])

In [13]:
matrix_2, vector_1

(array([[-4,  1, -5, -7],
        [ 4, -2,  3,  3],
        [ 8, -2, -6,  2]]),
 array([ 6, -5, -8, -5]))

In [14]:
np.dot(matrix_2, vector_1)

array([46, -5, 96])

## np.vdot

In [15]:
np.vdot(vector_1, vector_2)

np.int64(11)

## np.inner

In [16]:
np.inner(vector_1, vector_2)

np.int64(11)

In [17]:
np.inner(matrix_1, matrix_3)

array([[ 28, -36,   2,  18],
       [ 64,   6, -75,  -7],
       [-18,  45, -11, -37],
       [-73,  -6,  80,  14]])

## np.outer

In [18]:
vector_1, vector_2

(array([ 6, -5, -8, -5]), array([-2,  6, -1, -9]))

In [19]:
np.outer(a=vector_1, b=vector_2)

array([[-12,  36,  -6, -54],
       [ 10, -30,   5,  45],
       [ 16, -48,   8,  72],
       [ 10, -30,   5,  45]])

## np.matmul

In [20]:
np.matmul(vector_1, vector_2)

np.int64(11)

In [21]:
matrix_1, matrix_2

(array([[-4,  2,  6],
        [ 4,  9, -7],
        [ 7, -9,  1],
        [-5, -6,  3]]),
 array([[-4,  1, -5, -7],
        [ 4, -2,  3,  3],
        [ 8, -2, -6,  2]]))

In [22]:
np.matmul(matrix_1, matrix_2)

array([[ 72, -20, -10,  46],
       [-36,   0,  49, -15],
       [-56,  23, -68, -74],
       [ 20,   1, -11,  23]])

## np.linalg.det

In [23]:
matrix_4

array([[ 3,  7,  7],
       [ 5,  9, -4],
       [ 8,  8, -6]])

In [24]:
np.linalg.det(matrix_4)

np.float64(-304.00000000000006)

## np.linalg.inv

In [25]:
np.linalg.inv(matrix_4)

array([[ 0.07236842, -0.32236842,  0.29934211],
       [ 0.00657895,  0.24342105, -0.15460526],
       [ 0.10526316, -0.10526316,  0.02631579]])