In [1]:
import numpy as np
np.__version__

'2.3.4'

## Ufuncs

Vamos começar gerando 2 arrays de números inteiros para utilizarmos nos exercícios.

In [2]:
rng = np.random.default_rng(seed=2)

In [3]:
array_1 = rng.integers(low=-10, high=10, size=6).reshape(3, 2)
array_1

array([[ 6, -5],
       [-8, -5],
       [-2,  6]])

In [4]:
array_2 = rng.integers(low=-10, high=10, size=6).reshape(3,2)
array_2

array([[-1, -9],
       [-4,  2],
       [ 6,  4]])

### Funções matemáticas

#### `np.add`, `np.subtract`, `np.multiply`, `np.divide`

Utilize as 4 funções universais correspondentes às operações matemáticas básicas, utilizando `array_1` e `array_2`, nesta ordem.

Logo na sequência da chamada de cada função, repita a operação com os operadores matemáticos nativos do Python, `+`, `-`, `*` e `/`, para verificar que o resultado é o mesmo.

In [5]:
np.add(array_1, array_2)

array([[  5, -14],
       [-12,  -3],
       [  4,  10]])

In [6]:
array_1 + array_2

array([[  5, -14],
       [-12,  -3],
       [  4,  10]])

In [7]:
np.subtract(array_1, array_2)

array([[ 7,  4],
       [-4, -7],
       [-8,  2]])

In [8]:
array_1 - array_2

array([[ 7,  4],
       [-4, -7],
       [-8,  2]])

In [9]:
np.multiply(array_1, array_2)

array([[ -6,  45],
       [ 32, -10],
       [-12,  24]])

In [10]:
array_1 * array_2

array([[ -6,  45],
       [ 32, -10],
       [-12,  24]])

In [11]:
np.divide(array_1, array_2)

array([[-6.        ,  0.55555556],
       [ 2.        , -2.5       ],
       [-0.33333333,  1.5       ]])

In [12]:
array_1 / array_2

array([[-6.        ,  0.55555556],
       [ 2.        , -2.5       ],
       [-0.33333333,  1.5       ]])

#### `np.mod`

A forma mais comum de verificar se um número é *par* é observar se o seu *módulo* da divisão por 2 é igual a 0.

Utilize a função `np.mod` para verificar o módulo dos valores de `array_1` quando divididos por 2.

In [13]:
array_mod = np.mod(array_1, 2)

In [14]:
array_mod

array([[0, 1],
       [0, 1],
       [0, 0]])

Agora utilize o operador básico `==` para confirmar quais valores de `array_mod` são iguais a 0.

In [15]:
array_mod == 0

array([[ True, False],
       [ True, False],
       [ True,  True]])

Esta comparação indica quais valores são pares (`True`).

#### `np.divmod`

Muitas operações de divisão resultam em valores "quebrados". Às vezes nós queremos representar o resultado como valores inteiros, em um formato truncado, onde descartamos a parte decimal.

Utilize `np.divmod` para verificar qual a parte inteira e o resto da divisão de `array_1` por 4.

In [16]:
array_int, array_rest = np.divmod(array_1, 4)

In [17]:
array_int

array([[ 1, -2],
       [-2, -2],
       [-1,  1]])

👆 Este array representa o arredondamento por truncação dos resultados da operação.

In [18]:
array_rest

array([[2, 3],
       [0, 3],
       [2, 2]])

👆 Este é o resto da divisão.

#### `np.absolute`

Verifique quais são os valores absolutos de `array_2`.

In [19]:
np.absolute(array_2)

array([[1, 9],
       [4, 2],
       [6, 4]])

#### `np.diff`

Verifique a diferença entre os valores das colunas de `array_1`.

In [20]:
np.diff(array_1)

array([[-11],
       [  3],
       [  8]])

Verifique a diferença entre os valores das linhas de `array_2`.

In [21]:
np.diff(array_2, axis=0)

array([[-3, 11],
       [10,  2]])

#### `np.power`, `np.exp`, `np.log`

Calcule os valores de `array_2` elevados ao cubo.

In [22]:
np.power(array_2, 3)

array([[  -1, -729],
       [ -64,    8],
       [ 216,   64]])

Calcule o valor do número natural *e* elevado aos valores de `array_1`.

In [23]:
np.exp(array_1)

array([[4.03428793e+02, 6.73794700e-03],
       [3.35462628e-04, 6.73794700e-03],
       [1.35335283e-01, 4.03428793e+02]])

Calcule o logaritmo natural dos valores de `array_2`.

In [24]:
np.log(array_2)

C:\Users\joaoi\AppData\Local\Temp\ipykernel_17052\1547543613.py:1: RuntimeWarning: invalid value encountered in log
  np.log(array_2)


array([[       nan,        nan],
       [       nan, 0.69314718],
       [1.79175947, 1.38629436]])

#### `np.reciprocal`

Determine os valores recíprocos de `array_1`. Lembre-se que você precisa antes converter os valores do array para float.

In [25]:
np.reciprocal(array_1.astype(float))

array([[ 0.16666667, -0.2       ],
       [-0.125     , -0.2       ],
       [-0.5       ,  0.16666667]])

#### `np.sqrt`, `np.cbrt`

Obtenha a raiz quadrada dos valores de `array_1`.

In [26]:
np.sqrt(array_1)

C:\Users\joaoi\AppData\Local\Temp\ipykernel_17052\3607161969.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array_1)


array([[2.44948974,        nan],
       [       nan,        nan],
       [       nan, 2.44948974]])

Obtenha a raiz cúbica dos valores de `array_2`.

In [27]:
np.cbrt(array_2)

array([[-1.        , -2.08008382],
       [-1.58740105,  1.25992105],
       [ 1.81712059,  1.58740105]])

#### `np.gcd`, `np.lcm`

Calcule o maior divisor comum e o mínimo múltiplo comum entre `array_1` e `array_2`.

In [28]:
np.gcd(array_1, array_2)

array([[1, 1],
       [4, 1],
       [2, 2]])

In [29]:
np.lcm(array_1, array_2)

array([[ 6, 45],
       [ 8, 10],
       [ 6, 12]])

### Funções trigonométricas

Calcule o seno, o cosseno e a tangente de alguns ângulos importantes: 30, 45 e 90 graus. Lembre-se que você precisa antes coverter o ângulo para radianos.

In [30]:
radians_30 = np.radians(30)

In [31]:
np.sin(radians_30)

np.float64(0.49999999999999994)

👆 O valor exato é igual a 0.5.

In [32]:
np.cos(radians_30)

np.float64(0.8660254037844387)

In [33]:
np.tan(radians_30)

np.float64(0.5773502691896257)

In [34]:
radians_45 = np.radians(45)

In [35]:
print(np.sin(radians_45))

0.7071067811865476


In [36]:
print(np.cos(radians_45))

0.7071067811865476


In [37]:
print(np.tan(radians_45))

0.9999999999999999


👆 O valor exato é igual a 1.

In [38]:
radians_90 = np.radians(90)

In [39]:
print(np.sin(radians_90))

1.0


In [40]:
print(np.cos(radians_90))

6.123233995736766e-17


👆 O valor exato é igual a 0.

In [41]:
print(np.tan(radians_90))

1.633123935319537e+16


👆 O valor exato é *infinito*, pois $$tan(x) = \frac{sen(x)}{cos(x)}$$ e o cosseno de 90 graus é igual a 0. Por questões de arredondamento, o NumPy retorna um valor "muito alto" ao invés de expressar infinito.

### Funções de comparação

#### `np.maximum`,  `np.minimum`

Obtenha os valores máximos e mínimos comparando `array_1` com `array_2`.

In [42]:
np.maximum(array_1, array_2)

array([[ 6, -5],
       [-4,  2],
       [ 6,  6]])

In [43]:
np.minimum(array_1, array_2)

array([[-1, -9],
       [-8, -5],
       [-2,  4]])

#### `np.greater`,  `np.greater_equal`, `np.less`,  `np.less_equal`,  `np.not_equal`, `np.equal`

Compare `array_1` com `array_2` para verificar se seus valores são...

... maiores:

In [44]:
np.greater(array_1, array_2)

array([[ True,  True],
       [False, False],
       [False,  True]])

... menores ou iguais:

In [45]:
np.less_equal(array_1, array_2)

array([[False, False],
       [ True,  True],
       [ True, False]])

... diferentes:

In [46]:
np.not_equal(array_1, array_2)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

#### `logical_and`, `logical_or`, `logical_xor`, `logical_not`

Primeiro gere uma máscara booleana para verificar quais valores em `array_1` e `array_2` são pares.

In [47]:
array_1_mask = np.mod(array_1, 2) == 0

In [48]:
array_1_mask

array([[ True, False],
       [ True, False],
       [ True,  True]])

In [49]:
array_2_mask = np.mod(array_2, 2) == 0

In [50]:
array_2_mask

array([[False, False],
       [ True,  True],
       [ True,  True]])

Agora, com `logical_and`, verifique onde nos dois arrays os valores são pares.

In [51]:
np.logical_and(array_1_mask, array_2_mask)

array([[False, False],
       [ True, False],
       [ True,  True]])

Com `logical_or`, você pode verificar onde pelo menos um dos valores é par.

In [52]:
np.logical_or(array_1_mask, array_2_mask)

array([[ True, False],
       [ True,  True],
       [ True,  True]])

Você também pode verificar onde pelo menos um dos valores é ímpar com `logical_not`, sem precisar refazer as máscaras booleanas.

In [53]:
np.logical_not(array_1_mask, array_2_mask)

array([[False,  True],
       [False,  True],
       [False, False]])

#### `np.isclose`, `np.allclose`

Agora vamos gerar 2 novos arrays com valores reais a partir da amostragem de uma distribuição normal, com desvio padrão pequeno.

In [54]:
array_3 = rng.normal(loc=0, scale=0.0001, size=6).reshape(3, 2)

In [55]:
array_3

array([[-3.25422837e-05,  7.73806587e-05],
       [ 2.81210670e-05, -5.53822836e-05],
       [ 9.77567451e-05, -3.10556547e-05]])

In [56]:
array_4 = rng.normal(loc=0, scale=0.0001, size=6).reshape(3, 2)

In [57]:
array_4

array([[-3.28823904e-05, -7.92146755e-05],
       [ 4.54958071e-05, -9.91980517e-06],
       [ 5.45288714e-05, -6.07185700e-05]])

Verifique se os valores de `array_3` são próximos de `array_4` dentro da margem de tolerância 0.001.

In [58]:
np.isclose(a=array_3, b=array_4, atol=0.001)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

Verifique se todos os valores atendem a esta condição.

In [59]:
np.allclose(a=array_3, b=array_4, atol=0.001)

True

👆 Todos os valores são iguais dentro desta margem de tolerância.

E se a margem de tolerância for igual a 0.0001?

In [60]:
np.isclose(a=array_3, b=array_4, atol=0.0001)

array([[ True, False],
       [ True,  True],
       [ True,  True]])

In [61]:
np.allclose(a=array_3, b=array_4, atol=0.0001)

False

👆 Nem todos os valores são iguais dentro desta margem de tolerância.

#### `np.array_equal`

Gere uma **view** de `array_3` e confirme que a view é igual ao array com a função `np.array_equal`.

In [62]:
array_3_view = array_3.view()

In [63]:
np.array_equal(array_3, array_3_view)

True

### Funções float

#### `np.isfinite`, `np.isinf`, `np.isneginf`, `np.isnan`

Comece gerando um array com valores aleatórios inteiros no intervalo [-10, 11), organizados em um array no formato (3, 4).

In [64]:
array_5 = rng.integers(low=-11, high=10, size=12).reshape(3, 4)

In [65]:
array_5

array([[ -4,  -3, -11,  -8],
       [ -5,  -4,   1,  -1],
       [  3,   7,   7,   5]])

Agora gere um novo array somente com valores 0 ou 1, no mesmo formato. Você também pode utilizar `rng.integers` para isso.

In [66]:
array_6 = rng.integers(low=0, high=1, size=(3, 4))

In [67]:
array_6

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Determine a divisão de `array_5` por `array_6`.

In [68]:
array_div = np.divide(array_5, array_6)

C:\Users\joaoi\AppData\Local\Temp\ipykernel_17052\2565710344.py:1: RuntimeWarning: divide by zero encountered in divide
  array_div = np.divide(array_5, array_6)


In [69]:
array_div

array([[-inf, -inf, -inf, -inf],
       [-inf, -inf,  inf, -inf],
       [ inf,  inf,  inf,  inf]])

Verifique quais valores de `array_div` são:

... finitos:

In [70]:
np.isfinite(array_div)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

... infinitos:

In [71]:
np.isinf(array_div)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

... infinitos negativos:

In [72]:
np.isneginf(array_div)

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False, False, False, False]])

Agora determine o logaritmo na base 10 de `array_5`.

In [73]:
array_log_10 = np.log(array_5)

C:\Users\joaoi\AppData\Local\Temp\ipykernel_17052\3784087537.py:1: RuntimeWarning: invalid value encountered in log
  array_log_10 = np.log(array_5)


In [74]:
array_log_10

array([[       nan,        nan,        nan,        nan],
       [       nan,        nan, 0.        ,        nan],
       [1.09861229, 1.94591015, 1.94591015, 1.60943791]])

Quais desses valores são indeterminados ("not a number")?

In [75]:
np.isnan(array_5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### Funções float

#### `np.floor`, `np.ceil`, `np.trunc`

Gere um novo array com 10 valores aleatórios obtidos de uma distribuição normal, com média 0 e desvio padrão 1.

In [76]:
array_7 = rng.standard_normal(size=10)

In [77]:
array_7

array([-1.0107575 ,  0.783181  ,  2.05670282, -1.6384425 , -1.72941147,
       -1.50483141,  0.84145889,  0.12871566,  1.07834244,  0.72243087])

Arredonde os valores para...

... baixo:

In [78]:
np.ceil(array_7)

array([-1.,  1.,  3., -1., -1., -1.,  1.,  1.,  2.,  1.])

... cima:

In [79]:
np.floor(array_7)

array([-2.,  0.,  2., -2., -2., -2.,  0.,  0.,  1.,  0.])

... o valor inteiro mais próximo de 0:

In [80]:
np.trunc(array_7)

array([-1.,  0.,  2., -1., -1., -1.,  0.,  0.,  1.,  0.])