# **Funções universais**

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=2)

In [3]:
array_1 = rng.integers(low=-10, high=10, size=20).reshape(4, 5)
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [4]:
array_2 = rng.integers(low=-10, high=10, size=20).reshape(4, 5)
array_2

array([[ -4,   1,  -5,  -7,   4],
       [ -2,   3,   3,   8,  -2],
       [ -6,   2,   8,   9,   7],
       [  3,  -3,  -3, -10,  -7]])

## Funções matemáticas

### np.add, np.subtract, np.multiply e np.divide

In [5]:
np.add(array_1, array_2)

array([[  2,  -4, -13, -12,   2],
       [  4,   2,  -6,   4,   0],
       [  0,   6,  17,   2,  14],
       [ -6,  -2,  -8, -16,  -4]])

In [6]:
np.subtract(array_1, array_2)

array([[ 10,  -6,  -3,   2,  -6],
       [  8,  -4, -12, -12,   4],
       [ 12,   2,   1, -16,   0],
       [-12,   4,  -2,   4,  10]])

In [7]:
np.multiply(array_1, array_2)

array([[-24,  -5,  40,  35,  -8],
       [-12,  -3, -27, -32,  -4],
       [-36,   8,  72, -63,  49],
       [-27,  -3,  15,  60, -21]])

In [8]:
np.divide(array_1, array_2)

array([[-1.5       , -5.        ,  1.6       ,  0.71428571, -0.5       ],
       [-3.        , -0.33333333, -3.        , -0.5       , -1.        ],
       [-1.        ,  2.        ,  1.125     , -0.77777778,  1.        ],
       [-3.        , -0.33333333,  1.66666667,  0.6       , -0.42857143]])

In [9]:
np.add(array_1, 100)

array([[106,  95,  92,  95,  98],
       [106,  99,  91,  96, 102],
       [106, 104, 109,  93, 107],
       [ 91, 101,  95,  94, 103]])

### np.mod

In [10]:
np.mod(array_1, 2)

array([[0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1]])

### np.divmod

In [11]:
np.divmod(array_1, 2)

(array([[ 3, -3, -4, -3, -1],
        [ 3, -1, -5, -2,  1],
        [ 3,  2,  4, -4,  3],
        [-5,  0, -3, -3,  1]]),
 array([[0, 1, 0, 1, 0],
        [0, 1, 1, 0, 0],
        [0, 0, 1, 1, 1],
        [1, 1, 1, 0, 1]]))

### np.absolute

In [12]:
np.absolute(array_1)

array([[6, 5, 8, 5, 2],
       [6, 1, 9, 4, 2],
       [6, 4, 9, 7, 7],
       [9, 1, 5, 6, 3]])

### np.diff

In [13]:
np.diff(array_1)

array([[-11,  -3,   3,   3],
       [ -7,  -8,   5,   6],
       [ -2,   5, -16,  14],
       [ 10,  -6,  -1,   9]])

In [14]:
np.diff(array_1, axis=0)

array([[  0,   4,  -1,   1,   4],
       [  0,   5,  18,  -3,   5],
       [-15,  -3, -14,   1,  -4]])

In [15]:
np.diff(a=array_1, n=2)

array([[  8,   6,   0],
       [ -1,  13,   1],
       [  7, -21,  30],
       [-16,   5,  10]])

### np.power, np.exp e np.log

In [16]:
np.power(array_1, 2)

array([[36, 25, 64, 25,  4],
       [36,  1, 81, 16,  4],
       [36, 16, 81, 49, 49],
       [81,  1, 25, 36,  9]])

In [17]:
np.power(array_1, [[2], [2], [3], [3]])

array([[  36,   25,   64,   25,    4],
       [  36,    1,   81,   16,    4],
       [ 216,   64,  729, -343,  343],
       [-729,    1, -125, -216,   27]])

In [18]:
np.power(array_1, [[2, 2, 3, 3, 3]])

array([[  36,   25, -512, -125,   -8],
       [  36,    1, -729,  -64,    8],
       [  36,   16,  729, -343,  343],
       [  81,    1, -125, -216,   27]])

In [19]:
np.exp(array_1)

array([[4.03428793e+02, 6.73794700e-03, 3.35462628e-04, 6.73794700e-03,
        1.35335283e-01],
       [4.03428793e+02, 3.67879441e-01, 1.23409804e-04, 1.83156389e-02,
        7.38905610e+00],
       [4.03428793e+02, 5.45981500e+01, 8.10308393e+03, 9.11881966e-04,
        1.09663316e+03],
       [1.23409804e-04, 2.71828183e+00, 6.73794700e-03, 2.47875218e-03,
        2.00855369e+01]])

In [20]:
np.log(array_1)

C:\Users\joaoi\AppData\Local\Temp\ipykernel_14636\3647096076.py:1: RuntimeWarning: invalid value encountered in log
  np.log(array_1)


array([[1.79175947,        nan,        nan,        nan,        nan],
       [1.79175947,        nan,        nan,        nan, 0.69314718],
       [1.79175947, 1.38629436, 2.19722458,        nan, 1.94591015],
       [       nan, 0.        ,        nan,        nan, 1.09861229]])

### np.reciprocal

In [21]:
np.reciprocal(array_1.astype(float))

array([[ 0.16666667, -0.2       , -0.125     , -0.2       , -0.5       ],
       [ 0.16666667, -1.        , -0.11111111, -0.25      ,  0.5       ],
       [ 0.16666667,  0.25      ,  0.11111111, -0.14285714,  0.14285714],
       [-0.11111111,  1.        , -0.2       , -0.16666667,  0.33333333]])

### np.sqrt e np.cbrt

In [22]:
np.sqrt(array_1)

C:\Users\joaoi\AppData\Local\Temp\ipykernel_14636\3607161969.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array_1)


array([[2.44948974,        nan,        nan,        nan,        nan],
       [2.44948974,        nan,        nan,        nan, 1.41421356],
       [2.44948974, 2.        , 3.        ,        nan, 2.64575131],
       [       nan, 1.        ,        nan,        nan, 1.73205081]])

In [23]:
np.cbrt(array_1)

array([[ 1.81712059, -1.70997595, -2.        , -1.70997595, -1.25992105],
       [ 1.81712059, -1.        , -2.08008382, -1.58740105,  1.25992105],
       [ 1.81712059,  1.58740105,  2.08008382, -1.91293118,  1.91293118],
       [-2.08008382,  1.        , -1.70997595, -1.81712059,  1.44224957]])

### np.gcd e np.lcm

In [24]:
np.gcd(array_1, array_2)

array([[2, 1, 1, 1, 2],
       [2, 1, 3, 4, 2],
       [6, 2, 1, 1, 7],
       [3, 1, 1, 2, 1]])

In [25]:
np.lcm(array_1, array_2)

array([[12,  5, 40, 35,  4],
       [ 6,  3,  9,  8,  2],
       [ 6,  4, 72, 63,  7],
       [ 9,  3, 15, 30, 21]])