# **Funções universais**

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=2)

In [3]:
array_1 = rng.integers(low=-10, high=10, size=20).reshape(4, 5)
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [4]:
array_2 = rng.integers(low=-10, high=10, size=20).reshape(4, 5)
array_2

array([[ -4,   1,  -5,  -7,   4],
       [ -2,   3,   3,   8,  -2],
       [ -6,   2,   8,   9,   7],
       [  3,  -3,  -3, -10,  -7]])

## Funções matemáticas

### np.add, np.subtract, np.multiply e np.divide

In [5]:
np.add(array_1, array_2)

array([[  2,  -4, -13, -12,   2],
       [  4,   2,  -6,   4,   0],
       [  0,   6,  17,   2,  14],
       [ -6,  -2,  -8, -16,  -4]])

In [6]:
np.subtract(array_1, array_2)

array([[ 10,  -6,  -3,   2,  -6],
       [  8,  -4, -12, -12,   4],
       [ 12,   2,   1, -16,   0],
       [-12,   4,  -2,   4,  10]])

In [7]:
np.multiply(array_1, array_2)

array([[-24,  -5,  40,  35,  -8],
       [-12,  -3, -27, -32,  -4],
       [-36,   8,  72, -63,  49],
       [-27,  -3,  15,  60, -21]])

In [8]:
np.divide(array_1, array_2)

array([[-1.5       , -5.        ,  1.6       ,  0.71428571, -0.5       ],
       [-3.        , -0.33333333, -3.        , -0.5       , -1.        ],
       [-1.        ,  2.        ,  1.125     , -0.77777778,  1.        ],
       [-3.        , -0.33333333,  1.66666667,  0.6       , -0.42857143]])

In [9]:
np.add(array_1, 100)

array([[106,  95,  92,  95,  98],
       [106,  99,  91,  96, 102],
       [106, 104, 109,  93, 107],
       [ 91, 101,  95,  94, 103]])

### np.mod

In [10]:
np.mod(array_1, 2)

array([[0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1]])

### np.divmod

In [11]:
np.divmod(array_1, 2)

(array([[ 3, -3, -4, -3, -1],
        [ 3, -1, -5, -2,  1],
        [ 3,  2,  4, -4,  3],
        [-5,  0, -3, -3,  1]]),
 array([[0, 1, 0, 1, 0],
        [0, 1, 1, 0, 0],
        [0, 0, 1, 1, 1],
        [1, 1, 1, 0, 1]]))

### np.absolute

In [12]:
np.absolute(array_1)

array([[6, 5, 8, 5, 2],
       [6, 1, 9, 4, 2],
       [6, 4, 9, 7, 7],
       [9, 1, 5, 6, 3]])

### np.diff

In [13]:
np.diff(array_1)

array([[-11,  -3,   3,   3],
       [ -7,  -8,   5,   6],
       [ -2,   5, -16,  14],
       [ 10,  -6,  -1,   9]])

In [14]:
np.diff(array_1, axis=0)

array([[  0,   4,  -1,   1,   4],
       [  0,   5,  18,  -3,   5],
       [-15,  -3, -14,   1,  -4]])

In [15]:
np.diff(a=array_1, n=2)

array([[  8,   6,   0],
       [ -1,  13,   1],
       [  7, -21,  30],
       [-16,   5,  10]])

### np.power, np.exp e np.log

### np.reciprocal

### np.sqrt e np.cbrt

### np.gcd e np.lcm