# **Salvando e Carregando arrays**

In [1]:
import numpy as np

In [2]:
array_1 = np.array([0, 1, 2, 3, 4])
array_2 = np.array([5, 6, 7, 8, 9])

## np.save e np.load

In [3]:
np.save(file='array_1_file', arr=array_1)

In [4]:
array_1_loaded = np.load(file='./array_1_file.npy')
array_1_loaded

array([0, 1, 2, 3, 4])

## np.savez

In [5]:
np.savez('array_savez', array_1, array_2)

In [6]:
array_loaded = np.load('./array_savez.npz')
array_loaded

NpzFile './array_savez.npz' with keys: arr_0, arr_1

In [7]:
array_loaded['arr_0']

array([0, 1, 2, 3, 4])

In [8]:
array_loaded['arr_1']

array([5, 6, 7, 8, 9])

## np.savez_compressed

In [9]:
np.savez_compressed('arrays_compacted', array_1, array_2)

In [10]:
array_compacted_loaded = np.load('./arrays_compacted.npz')
array_compacted_loaded

NpzFile './arrays_compacted.npz' with keys: arr_0, arr_1

In [11]:
array_compacted_loaded["arr_0"], array_compacted_loaded["arr_1"]

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

## np.savetxt e np.loadtxt

In [12]:
array_2d = np.vstack([array_1, array_2])
array_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
np.savetxt(fname='array_csv.csv', X=array_2d)

In [14]:
np.savetxt(fname='array_csv.csv', X=array_2d, fmt='%s')

In [15]:
np.savetxt(fname='array_csv.csv', X=array_2d, fmt='%s', delimiter=',')

In [16]:
array_csv_loaded = np.loadtxt(fname='./array_csv.csv', dtype=int, delimiter=',')
array_csv_loaded

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])