In [1]:
import numpy as np
np.__version__

'2.3.4'

Comece gerando dois arrays:
- o primeiro através de amostragem de uma distribuição normal com média 10 e desvio-padrão 2, no formato 5x3.
- o segundo através de amostragem de uma distribuição uniforme com mínimo 25 e máximo 50, no formato 3x4x2.

Para garantir a reprodutibilidade, utilize seed igual a 10.

In [2]:
rng = np.random.default_rng(seed=10)

In [3]:
array_1 = rng.normal(10, 2, size=(5,3))

In [4]:
array_1

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

In [5]:
array_2 = rng.uniform(25, 50, size=(3,4,2))

In [6]:
array_2

array([[[48.33596177, 28.62486737],
        [43.63950528, 28.48378485],
        [47.6632189 , 30.65286084],
        [46.33099375, 32.65794664]],

       [[49.24575921, 37.94585534],
        [33.06186397, 32.06083793],
        [40.1466249 , 33.34411142],
        [41.96621934, 28.86062676]],

       [[31.24438798, 46.74735615],
        [40.00919551, 31.5495764 ],
        [28.73537251, 28.41972874],
        [31.22302344, 34.57061666]]])

#### `np.save`, `np.load`

Salve `array_1` no arquivo `array_1_file`.

In [7]:
np.save(file='array_1_file', arr=array_1)

Recarregue o array salvo.

In [8]:
array_1_loaded = np.load(file='./array_1_file.npy')

In [9]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

Verifique que os dois arrays são iguais com `np.array_equal`.

In [10]:
np.array_equal(array_1_loaded, array_1)

True

#### `np.savez`

Salve os dois arrays em um único arquivo `npz`.

In [11]:
np.savez("arrays_savez", array_1, array_2)

Recarregue o arquivo e restaure os dois arrays.

In [12]:
arrays_loaded = np.load('./arrays_savez.npz')

In [13]:
arrays_loaded

NpzFile './arrays_savez.npz' with keys: arr_0, arr_1

In [14]:
array_1_loaded = arrays_loaded['arr_0']

In [15]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

In [16]:
array_2_loaded = arrays_loaded['arr_1']

In [17]:
array_2_loaded

array([[[48.33596177, 28.62486737],
        [43.63950528, 28.48378485],
        [47.6632189 , 30.65286084],
        [46.33099375, 32.65794664]],

       [[49.24575921, 37.94585534],
        [33.06186397, 32.06083793],
        [40.1466249 , 33.34411142],
        [41.96621934, 28.86062676]],

       [[31.24438798, 46.74735615],
        [40.00919551, 31.5495764 ],
        [28.73537251, 28.41972874],
        [31.22302344, 34.57061666]]])

#### `np.savez_compressed`

Salve e recarregue os dois arrays em um único arquivo compactado.

In [18]:
np.savez_compressed('arrays_compacted', array_1, array_2)

In [19]:
arrays_compacted_loaded = np.load('./arrays_compacted.npz')

In [20]:
arrays_compacted_loaded

NpzFile './arrays_compacted.npz' with keys: arr_0, arr_1

#### `np.savetxt`, `np.loadtxt`

Salve `array_1` em formato `csv`.

In [21]:
np.savetxt(fname='array_csv.csv', X=array_1)

Use o comando do Linux abaixo para visualizar como os dados foram salvos no arquivo.

In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('./array_csv.csv')
df

7.793323101868935510e+00 8.549950719511119956e+00 8.436389485363886109e+00
0  1.053395171278878450e+01 9.502838541122217819e...                        
1  1.168608514160867529e+01 1.171587309895153695e...                        
2  9.098462803835166923e+00 8.490135436352497678e...                        
3  9.312290284411478325e+00 9.897239812426132488e...

Recarregue este array a partir do arquivo.

In [24]:
array_1_loaded = np.loadtxt(fname='./array_csv.csv')

In [25]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

Use `np.array_equal` para verificar que, mesmo quando salvo como `csv`, o array recarregado é igual ao array original.

In [26]:
np.array_equal(array_1, array_1_loaded)

True