# **Números aleatórios**

In [1]:
import numpy as np
import matplotlib as plt

## Gerador de dados aleatórios

### rng.random

In [2]:
rng = np.random.default_rng(seed=1)
rng.random()

0.5118216247002567

In [3]:
rng = np.random.default_rng(seed=1)
rng.random(size=10)

array([0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145,
       0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911])

In [4]:
rng = np.random.default_rng(seed=1)
rng.random(size=(5, 2))

array([[0.51182162, 0.9504637 ],
       [0.14415961, 0.94864945],
       [0.31183145, 0.42332645],
       [0.82770259, 0.40919914],
       [0.54959369, 0.02755911]])

### rgn.intergers

In [5]:
rng.integers(4, size=5)

array([3, 3, 3, 2, 3])

In [6]:
rng.integers(low=10, high=50, size=5)

array([23, 28, 41, 14, 22])

In [7]:
rng.integers(low=10,high=[15, 54, 100])

array([10, 29, 97])

### rgn.choice

In [8]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
rng.choice(a=array)

np.int64(1)

In [10]:
rng.choice(a=array, size=5)

array([3, 4, 9, 2, 5])

In [11]:
rng.choice(a=array, size=10, replace=False)

array([4, 6, 9, 3, 2, 1, 5, 0, 8, 7])

In [12]:
array = np.array([1, 2, 3])
p = np.array([0.5, 0.4, 0.1])

In [13]:
rng.choice(a=array, size=10, p=p)

array([3, 2, 1, 2, 2, 2, 3, 1, 2, 1])

In [14]:
array_2d = np.arange(0, 20).reshape(4, 5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
rng.choice(a=array_2d, size=2, axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
rng.choice(a=array_2d, size=2, axis=1)

array([[ 0,  2],
       [ 5,  7],
       [10, 12],
       [15, 17]])

## Permutações

### rgn.shuffle

In [17]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
rng.shuffle(array)
array

array([6, 3, 2, 0, 5, 4, 1, 9, 7, 8])

In [19]:
array = np.arange(20).reshape(4, 5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
rng.shuffle(array, axis=0)
array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [21]:
array = np.arange(20).reshape(4, 5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
rng.shuffle(array, axis=1)
array

array([[ 3,  0,  2,  1,  4],
       [ 8,  5,  7,  6,  9],
       [13, 10, 12, 11, 14],
       [18, 15, 17, 16, 19]])

### rgn.permutation

In [23]:
rng.permutation(10)

array([6, 2, 3, 1, 9, 4, 8, 5, 7, 0])

In [24]:
array = np.arange(20).reshape(4, 5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
rng.permutation(array, axis=0)

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [26]:
rng.permutation(array, axis=1)

array([[ 1,  0,  2,  4,  3],
       [ 6,  5,  7,  9,  8],
       [11, 10, 12, 14, 13],
       [16, 15, 17, 19, 18]])

### rgn.permuted

In [27]:
array = np.arange(20).reshape(4, 5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
rng.permuted(array, axis=0)

array([[ 5,  6, 17,  3, 19],
       [15, 16,  7, 13,  9],
       [ 0, 11,  2, 18, 14],
       [10,  1, 12,  8,  4]])

In [29]:
rng.permuted(array, axis=1)

array([[ 2,  3,  4,  1,  0],
       [ 5,  6,  8,  9,  7],
       [11, 10, 13, 12, 14],
       [15, 17, 19, 18, 16]])