# **Métodos Numpy**

In [1]:
import numpy as np

In [2]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## Tolist

In [3]:
array_3d.tolist()

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]

In [4]:
type(array_3d.tolist())

list

## item

In [5]:
array_3d[1, 0, 2]

np.int64(15)

In [6]:
array_3d.item((1, 0, 2))

15

In [7]:
array_3d.item(14)

15

## itemset

In [8]:
# array_3d.itemset(14, 50)
# array_3d

## view

In [9]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [10]:
array_view = array_3d.view()
array_view

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [11]:
array_view[0, 0, 0] = 0
array_view

array([[[ 0,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [12]:
array_3d

array([[[ 0,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## copy

In [13]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [14]:
array_copy = array_3d.copy()
array_copy

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [15]:
array_copy[0, 0, 0] = 99
array_copy

array([[[99,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [16]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## fill

In [17]:
array_3d.fill(55)

In [18]:
array_3d

array([[[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]],

       [[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]]])

## **Manipulação de formatos**

## reshape

In [19]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [20]:
array_3d.shape

(2, 4, 3)

In [21]:
array_3d = array_3d.reshape(4, 3, 2)
array_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [22]:
array_3d = array_3d.reshape(4, 3, -1)
array_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [23]:
array_3d = array_3d.reshape(4, -1, 2)
array_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

## transpose

In [24]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [25]:
array_transpose = array_3d.transpose((1, 0, 2))
array_transpose

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]])

In [26]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array_2d.transpose((1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
array_2d.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

## swapaxes

In [29]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [30]:
array_3d.swapaxes(1, 0)

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]])

## flatten

In [31]:
array_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## ravel

In [32]:
array_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [33]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## squeeze

In [34]:
array_axis_size_1 = array_3d.reshape(8, 1, 3)
array_axis_size_1

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]],

       [[16, 17, 18]],

       [[19, 20, 21]],

       [[22, 23, 24]]])

In [35]:
array_axis_size_1.shape

(8, 1, 3)

In [36]:
array_squeeze = array_axis_size_1.squeeze()

In [37]:
array_squeeze

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

## **Métodos de seleção e manipulação de itens**

### take

In [38]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [39]:
array_3d.take(indices=[1, 5, 10, 12])

array([ 2,  6, 11, 13])

In [40]:
array_3d.take(indices=[[1, 5], [15, 16]])

array([[ 2,  6],
       [16, 17]])

### put

In [41]:
array_3d.put(indices=[1, 5, 10, 12], values=[52, 56, 61, 63])
array_3d

array([[[ 1, 52,  3],
        [ 4,  5, 56],
        [ 7,  8,  9],
        [10, 61, 12]],

       [[63, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

### repeat

In [42]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [43]:
array_3d.repeat(repeats=2)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17,
       18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24])

In [44]:
array_3d.repeat(repeats=2, axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

### sort

In [45]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9]
])
array_2d.sort(axis=0)

In [46]:
array_2d

array([[ 8,  2,  7],
       [10,  3,  9]])

In [47]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9]
])
array_2d.sort(axis=1)

In [48]:
array_2d

array([[ 3,  7, 10],
       [ 2,  8,  9]])

### argsort

In [49]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9]
])

In [50]:
indices = array_2d.argsort(axis=0)
indices

array([[1, 1, 0],
       [0, 0, 1]])

In [51]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9]
])
indices = array_2d.argsort(axis=1)
indices

array([[1, 2, 0],
       [1, 0, 2]])

### searchsorted

In [52]:
array_1d = np.array([2, 3, 7, 8, 9, 10])

In [53]:
array_1d.searchsorted([1, 4, 11])

array([0, 2, 6])

### diagonal

In [54]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9],
    [11, 4, 1]
])
array_2d.diagonal()

array([10,  2,  1])

## Métodos para cálculo

In [55]:
array_2d = np.array([
    [4, 2, 12],
    [10, 5, 6],
    [1, 11, 9],
    [7, 8, 3]
])
array_2d

array([[ 4,  2, 12],
       [10,  5,  6],
       [ 1, 11,  9],
       [ 7,  8,  3]])

### max

In [56]:
array_2d.max(axis=0)

array([10, 11, 12])

In [57]:
array_2d.max(axis=1)

array([12, 10, 11,  8])

In [58]:
array_2d.max()

np.int64(12)

In [59]:
array_2d_ax_1_kd = array_2d.max(axis=1, keepdims=True)
array_2d_ax_1_kd

array([[12],
       [10],
       [11],
       [ 8]])

In [60]:
array_2d_ax_1_kd.shape, array_2d.shape

((4, 1), (4, 3))

### argmax

In [61]:
array_2d

array([[ 4,  2, 12],
       [10,  5,  6],
       [ 1, 11,  9],
       [ 7,  8,  3]])

In [62]:
array_2d.argmax(axis=0)

array([1, 2, 0])

In [63]:
array_2d.argmax(axis=1)

array([2, 0, 1, 1])

In [64]:
array_2d.argmax()

np.int64(2)

### min e argmin

In [65]:
array_2d

array([[ 4,  2, 12],
       [10,  5,  6],
       [ 1, 11,  9],
       [ 7,  8,  3]])

In [66]:
array_2d.argmin(axis=0)

array([2, 0, 3])

In [67]:
array_2d.argmin(axis=1)

array([1, 1, 0, 2])

In [68]:
array_2d.argmin()

np.int64(6)

In [69]:
array_2d.min(axis=0)

array([1, 2, 3])

In [70]:
array_2d.min(axis=1)

array([2, 5, 1, 3])

In [71]:
array_2d.min()

np.int64(1)

### ptp (peak to peak)

In [72]:
array_2d

array([[ 4,  2, 12],
       [10,  5,  6],
       [ 1, 11,  9],
       [ 7,  8,  3]])

In [73]:
np.ptp(array_2d, axis=0)

array([9, 9, 9])

In [74]:
array_2d.max(axis=0), array_2d.min(axis=0)

(array([10, 11, 12]), array([1, 2, 3]))

In [75]:
array_2d.max(axis=0) - array_2d.min(axis=0)

array([9, 9, 9])

In [76]:
np.ptp(array_2d)

np.int64(11)

### clip

In [77]:
array_2d = np.arange(1, 13).reshape(4, 3)
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
array_2d.clip(min=3, max=10)

array([[ 3,  3,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 10, 10]])

### round

In [79]:
array_2d = np.linspace(0, 1, 12).reshape(4, 3)
array_2d

array([[0.        , 0.09090909, 0.18181818],
       [0.27272727, 0.36363636, 0.45454545],
       [0.54545455, 0.63636364, 0.72727273],
       [0.81818182, 0.90909091, 1.        ]])

In [80]:
array_2d.round(decimals=2)

array([[0.  , 0.09, 0.18],
       [0.27, 0.36, 0.45],
       [0.55, 0.64, 0.73],
       [0.82, 0.91, 1.  ]])

### sum

In [81]:
array_2d = np.arange(1, 13).reshape(4, 3)
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [82]:
array_2d.sum(axis=0)

array([22, 26, 30])

In [83]:
array_2d.sum(axis=1)

array([ 6, 15, 24, 33])

In [84]:
array_2d.sum()

np.int64(78)

### cumsum

In [85]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [86]:
array_2d.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18],
       [22, 26, 30]])

In [87]:
array_2d.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24],
       [10, 21, 33]])

In [88]:
array_2d.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

### mean

In [89]:
array_2d.mean(axis=0)

array([5.5, 6.5, 7.5])

In [90]:
array_2d.mean(axis=1)

array([ 2.,  5.,  8., 11.])

In [91]:
array_2d.mean()

np.float64(6.5)

### var

In [92]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
array_2d.var(axis=0)

array([11.25, 11.25, 11.25])

In [94]:
array_2d.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

In [95]:
array_2d.var()

np.float64(11.916666666666666)

### std

In [96]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
array_2d.std(axis=0)

array([3.35410197, 3.35410197, 3.35410197])

In [98]:
array_2d.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658, 0.81649658])

In [99]:
array_2d.std()

np.float64(3.452052529534663)

### prod e cumprod

In [100]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [101]:
array_2d.prod(axis=0)

array([ 280,  880, 1944])

In [103]:
array_2d.prod(axis=1)

array([   6,  120,  504, 1320])

In [104]:
array_2d.prod()

np.int64(479001600)

In [105]:
array_2d.cumprod(axis=1)

array([[   1,    2,    6],
       [   4,   20,  120],
       [   7,   56,  504],
       [  10,  110, 1320]])

In [106]:
array_2d.cumprod(axis=0)

array([[   1,    2,    3],
       [   4,   10,   18],
       [  28,   80,  162],
       [ 280,  880, 1944]])

In [107]:
array_2d.cumprod()

array([        1,         2,         6,        24,       120,       720,
            5040,     40320,    362880,   3628800,  39916800, 479001600])

### all e any

In [108]:
array_2d = np.arange(1, 13).reshape(4, 3)
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
array_2d_gt_0 = array_2d > 0
array_2d_gt_0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [110]:
array_2d_gt_0.all()

np.True_

In [111]:
array_2d_gt_0.all(axis=0)

array([ True,  True,  True])

In [112]:
array_2d_gt_5 = array_2d > 5
array_2d_gt_5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [113]:
array_2d_gt_5.all()

np.False_

In [114]:
array_2d_gt_5.all(axis=0)

array([False, False, False])

In [115]:
array_2d_gt_5.all(axis=1)

array([False, False,  True,  True])

In [116]:
array_2d_gt_5.any()

np.True_

In [117]:
array_2d_gt_5.any(axis=1)

array([False,  True,  True,  True])

In [118]:
array_2d_gt_5.any(axis=0)

array([ True,  True,  True])

In [119]:
array_2d_gt_12 = array_2d > 12
array_2d_gt_12

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [120]:
array_2d_gt_12.all()

np.False_

In [121]:
array_2d_gt_12.any()

np.False_