# **Métodos Numpy**

In [1]:
import numpy as np

In [2]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## Tolist

In [3]:
array_3d.tolist()

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]

In [4]:
type(array_3d.tolist())

list

## item

In [5]:
array_3d[1, 0, 2]

np.int64(15)

In [6]:
array_3d.item((1, 0, 2))

15

In [7]:
array_3d.item(14)

15

## itemset

In [8]:
# array_3d.itemset(14, 50)
# array_3d

## view

In [9]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [10]:
array_view = array_3d.view()
array_view

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [11]:
array_view[0, 0, 0] = 0
array_view

array([[[ 0,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [12]:
array_3d

array([[[ 0,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## copy

In [13]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [14]:
array_copy = array_3d.copy()
array_copy

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [15]:
array_copy[0, 0, 0] = 99
array_copy

array([[[99,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [16]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## fill

In [17]:
array_3d.fill(55)

In [18]:
array_3d

array([[[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]],

       [[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]]])

## **Manipulação de formatos**

## reshape

In [19]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [20]:
array_3d.shape

(2, 4, 3)

In [21]:
array_3d = array_3d.reshape(4, 3, 2)
array_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [22]:
array_3d = array_3d.reshape(4, 3, -1)
array_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [23]:
array_3d = array_3d.reshape(4, -1, 2)
array_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

## transpose

In [24]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [25]:
array_transpose = array_3d.transpose((1, 0, 2))
array_transpose

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]])

In [26]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array_2d.transpose((1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
array_2d.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

## swapaxes

In [29]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [30]:
array_3d.swapaxes(1, 0)

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]])

## flatten

In [31]:
array_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## ravel

In [32]:
array_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [33]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## squeeze

In [34]:
array_axis_size_1 = array_3d.reshape(8, 1, 3)
array_axis_size_1

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]],

       [[16, 17, 18]],

       [[19, 20, 21]],

       [[22, 23, 24]]])

In [35]:
array_axis_size_1.shape

(8, 1, 3)

In [36]:
array_squeeze = array_axis_size_1.squeeze()

In [37]:
array_squeeze

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

## **Métodos de seleção e manipulação de itens**

### take

In [38]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [39]:
array_3d.take(indices=[1, 5, 10, 12])

array([ 2,  6, 11, 13])

In [42]:
array_3d.take(indices=[[1, 5], [15, 16]])

array([[ 2,  6],
       [16, 17]])

### put

In [43]:
array_3d.put(indices=[1, 5, 10, 12], values=[52, 56, 61, 63])
array_3d

array([[[ 1, 52,  3],
        [ 4,  5, 56],
        [ 7,  8,  9],
        [10, 61, 12]],

       [[63, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

### repeat

In [44]:
array_3d = np.arange(1, 25).reshape(2, 4 ,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [45]:
array_3d.repeat(repeats=2)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17,
       18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24])

In [46]:
array_3d.repeat(repeats=2, axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

### sort

In [47]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9]
])
array_2d.sort(axis=0)

In [48]:
array_2d

array([[ 8,  2,  7],
       [10,  3,  9]])

In [51]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9]
])
array_2d.sort(axis=1)

In [52]:
array_2d

array([[ 3,  7, 10],
       [ 2,  8,  9]])

### argsort

In [53]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9]
])

In [54]:
indices = array_2d.argsort(axis=0)
indices

array([[1, 1, 0],
       [0, 0, 1]])

In [55]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9]
])
indices = array_2d.argsort(axis=1)
indices

array([[1, 2, 0],
       [1, 0, 2]])

### searchsorted

In [56]:
array_1d = np.array([2, 3, 7, 8, 9, 10])

In [57]:
array_1d.searchsorted([1, 4, 11])

array([0, 2, 6])

### diagonal

In [58]:
array_2d = np.array([
    [10, 3, 7],
    [8, 2, 9],
    [11, 4, 1]
])
array_2d.diagonal()

array([10,  2,  1])