# **Estatística**

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=5)

In [3]:
vector_1 = rng.integers(low=-10, high=10, size=4)
vector_1

array([  3,   6, -10,   6])

In [4]:
matrix_1 = rng.integers(low=-10, high=10, size=(4, 3))
matrix_1

array([[ -1,   0,   2],
       [ -5,   9,  -9],
       [ -5,  -3,   1],
       [ -2,  -8, -10]])

## np.percentile

In [5]:
np.percentile(a=vector_1, q=10)

np.float64(-6.1)

In [6]:
np.percentile(a=vector_1, q=50)

np.float64(4.5)

In [7]:
np.percentile(a=vector_1, q=90)

np.float64(6.0)

In [8]:
np.percentile(a=matrix_1, q=10)

np.float64(-8.9)

## np.quantile

In [9]:
np.quantile(a=vector_1, q=0.1)

np.float64(-6.1)

In [10]:
np.quantile(a=vector_1, q=0.5)

np.float64(4.5)

In [11]:
np.quantile(a=matrix_1, q=0.1)

np.float64(-8.9)

In [12]:
np.quantile(a=matrix_1, q=0.5, axis=1)

array([ 0., -5., -3., -8.])

## np.median, np.mean e np.average

In [13]:
np.median(a=vector_1)

np.float64(4.5)

In [14]:
np.median(matrix_1, axis=1)

array([ 0., -5., -3., -8.])

In [15]:
np.mean(vector_1)

np.float64(1.25)

In [16]:
np.mean(matrix_1)

np.float64(-2.5833333333333335)

In [17]:
np.mean(matrix_1, axis=1)

array([ 0.33333333, -1.66666667, -2.33333333, -6.66666667])

In [18]:
np.average(a=vector_1, weights=[0.15, 0.25, 0.4, 0.2])

np.float64(-0.8499999999999996)

## np.std, np.var

## np.cov

## np.corrcoef

## np.histogram