# **Estatística**

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=5)

In [3]:
vector_1 = rng.integers(low=-10, high=10, size=4)
vector_1

array([  3,   6, -10,   6])

In [4]:
matrix_1 = rng.integers(low=-10, high=10, size=(4, 3))
matrix_1

array([[ -1,   0,   2],
       [ -5,   9,  -9],
       [ -5,  -3,   1],
       [ -2,  -8, -10]])

## np.percentile

In [5]:
np.percentile(a=vector_1, q=10)

np.float64(-6.1)

In [6]:
np.percentile(a=vector_1, q=50)

np.float64(4.5)

In [7]:
np.percentile(a=vector_1, q=90)

np.float64(6.0)

In [8]:
np.percentile(a=matrix_1, q=10)

np.float64(-8.9)

## np.quantile

In [9]:
np.quantile(a=vector_1, q=0.1)

np.float64(-6.1)

In [10]:
np.quantile(a=vector_1, q=0.5)

np.float64(4.5)

In [11]:
np.quantile(a=matrix_1, q=0.1)

np.float64(-8.9)

In [12]:
np.quantile(a=matrix_1, q=0.5, axis=1)

array([ 0., -5., -3., -8.])

## np.median, np.mean e np.average

In [13]:
np.median(a=vector_1)

np.float64(4.5)

In [14]:
np.median(matrix_1, axis=1)

array([ 0., -5., -3., -8.])

In [15]:
np.mean(vector_1)

np.float64(1.25)

In [16]:
np.mean(matrix_1)

np.float64(-2.5833333333333335)

In [17]:
np.mean(matrix_1, axis=1)

array([ 0.33333333, -1.66666667, -2.33333333, -6.66666667])

In [18]:
np.average(a=vector_1, weights=[0.15, 0.25, 0.4, 0.2])

np.float64(-0.8499999999999996)

## np.std, np.var

In [19]:
np.std(a=vector_1)

np.float64(6.609652033201143)

In [20]:
np.std(a=matrix_1, axis=1)

array([1.24721913, 7.7172246 , 2.49443826, 3.39934634])

In [21]:
np.var(vector_1)

np.float64(43.6875)

In [22]:
np.var(a=matrix_1, axis=1)

array([ 1.55555556, 59.55555556,  6.22222222, 11.55555556])

## np.cov

In [23]:
vector_1

array([  3,   6, -10,   6])

In [24]:
np.cov(m=vector_1)

array(58.25)

In [25]:
vector_2 = 3 * vector_1
vector_2

array([  9,  18, -30,  18])

In [26]:
np.cov(m=vector_2)

array(524.25)

In [27]:
np.cov(m=vector_1, y=vector_2)

array([[ 58.25, 174.75],
       [174.75, 524.25]])

## np.corrcoef

In [28]:
np.corrcoef(x=vector_1, y=vector_1)

array([[1., 1.],
       [1., 1.]])

In [29]:
np.corrcoef(x=vector_1, y=vector_2)

array([[1., 1.],
       [1., 1.]])

## np.histogram

In [30]:
vector_3 = rng.integers(low=-10, high=10, size=100)
vector_3

array([-10, -10,  -8,   9,  -7,   3,   5,  -6,  -5,  -2,  -5,   9,  -7,
         7,   5,   6,  -8,  -3,   2,  -1,   3,   3,   3,  -9,   9,   1,
         8,  -5,  -3,   7,  -7,  -9,  -3,   3,  -8,   7,  -4,  -6,   0,
         7,   7,   7,  -4, -10,   5,   4,   5, -10, -10,   0,  -4,  -2,
         8,  -6,   0,  -4,  -5,   6,  -7,  -4,  -8,  -8,  -5,   3,   1,
        -2,  -7,   5,   5,  -6,  -9,  -4,  -8,   5,   0,   0,  -5,   0,
         9,  -6,   5, -10,  -4,   8,   7,  -9,   6,   6,  -1,  -3,   9,
         9,   3,  -3,  -6,   8,  -5,   1,   3,  -6])

In [31]:
hist, bin_edges = np.histogram(a=vector_3, bins=4)
hist, bin_edges

(array([28, 24, 19, 29]), array([-10.  ,  -5.25,  -0.5 ,   4.25,   9.  ]))

In [32]:
hist, bin_edges = np.histogram(a=vector_3, bins=4, density=True)
hist, bin_edges

(array([0.05894737, 0.05052632, 0.04      , 0.06105263]),
 array([-10.  ,  -5.25,  -0.5 ,   4.25,   9.  ]))

## np.bincount

In [33]:
vector_4 = np.arange(6)
vector_4

array([0, 1, 2, 3, 4, 5])

In [34]:
np.bincount(vector_4)

array([1, 1, 1, 1, 1, 1])

In [35]:
vector_5 = rng.integers(low=0, high=10, size=6)
vector_5

array([3, 7, 1, 6, 9, 6])

In [36]:
np.bincount(vector_5)

array([0, 1, 0, 1, 0, 0, 2, 1, 0, 1])