# **Broadcasting**

In [1]:
import numpy as np

In [2]:
list_a = [1, 2, 3, 4]
list_a + 5

TypeError: can only concatenate list (not "int") to list

In [3]:
list_b = []
for i in list_a:
    list_b.append(i + 5)
print(list_b)

[6, 7, 8, 9]


In [4]:
array_a = np.array(list_a)
array_a + 5

array([6, 7, 8, 9])

In [5]:
array_b = np.array([[5],
                    [10]])

In [6]:
array_b

array([[ 5],
       [10]])

In [7]:
array_b.shape

(2, 1)

In [8]:
array_a + array_b

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [9]:
array_b = np.array([[5,6],
                    [10,11]])

In [10]:
array_b.shape

(2, 2)

In [11]:
array_a + array_b

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 