In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.2'

Neste módulo, você será convidado a refazer alguns dos exemplos apresentados na aula, para fixação dos conceitos.

### NumPy x Listas

#### Tamanho fixo

Abaixo vamos instanciar um array com 4 elementos.

In [3]:
array_a = np.array([0, 1, 2, 3])

Utilizando a função `np.append`, adicione o elemento `4` no final deste array. Lembre-se que este elemento deve estar "envelopado" em uma lista: `[4]`. Coloque o resultado em novo array chamado `array_b` e exiba o resultado.

In [4]:
array_b = np.append(array_a, [4])
array_b

array([0, 1, 2, 3, 4])

In [ ]:
array_b

array([0, 1, 2, 3, 4])

Agora, utilizando a função `id` do Python e o comparador `==`, mostre que os dois arrays têm endereços diferentes na memória, o que mostra que `array_b` é diferente de `array_a`.

💡 Isto ocorre porque, no NumPy, os arrays têm **tamanho fixo**. Se você adicionar elementos no array, um novo array é criado.

In [6]:
print(id(array_a) == id(array_b))

False


#### Homogêneo

Instancie um array `array_c` com 3 elementos:
- o número `3` (inteiro)
- o número `7.9` (float)
- o valor `False` (booleano)

Exiba este array.

In [10]:
array_c = np.array([3, 7.9, False])
array_c

array([3. , 7.9, 0. ])

In [ ]:
array_c

array([3. , 7.9, 0. ])

Utilizando um loop `for` para iterar sobre os elementos de `array_c`,  exiba na tela (`print`) o próprio elemento, e o tipo de cada elemento do array, utilizando a função `type`.

In [11]:
for i in array_c:
    print(i, type(i))

3.0 <class 'numpy.float64'>
7.9 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>


💡 Observe que, para manter a homogeneidade do array, todos os elementos foram convertidos para o tipo `np.float`.

Agora, utilizando o método `dtype` do array, exiba o tipo de dado que ele armazena.

In [12]:
array_c.dtype

dtype('float64')

💡 Perceba que o array têm o mesmo tipo de dado que seus elementos.

#### Vetorização

Instancie um array `array_d` com os valores `10`, `11`, `12` e `13`, e um array `array_e` com os valores `1`, `2`, `3` e `4`.

Exiba estes dois arrays.

In [13]:
array_d = np.array([10, 11, 12, 13])
array_e = np.array([1, 2, 3, 4])

array_d, array_e

(array([10, 11, 12, 13]), array([1, 2, 3, 4]))

Agora, realize as 4 operações matemáticas básicas (soma, subtração, multiplicação e divisão) utilizando os operadores nativos do Python (`+`, `-`, `*`, `/`). Exiba os resultados diretamente, sem armazená-los em uma variável antes.

In [14]:
array_d + array_e

array([11, 13, 15, 17])

In [15]:
array_d - array_e

array([9, 9, 9, 9])

In [16]:
array_d * array_e

array([10, 22, 36, 52])

In [17]:
array_d / array_e

array([10.  ,  5.5 ,  4.  ,  3.25])

💡 O uso dos operadores básicos só é possível graças à propriedade vetorial dos arrays do NumPy, que permite operações matemáticas elemento-a-elemento entre arrays.

#### Broadcasting

Vamos reutilizar o `array_d` para demonstrar a propriedade de broadcasting.

Utilize os 4 operadores matemáticos básicos para somar, subtrair, multiplicar e dividir o valor `2` de cada elemento do array.

Printe os resultados diretamente na tela.

In [18]:
array_d + 2

array([12, 13, 14, 15])

In [19]:
array_d - 2

array([ 8,  9, 10, 11])

In [20]:
array_d * 2

array([20, 22, 24, 26])

In [21]:
array_d / 2

array([5. , 5.5, 6. , 6.5])

💡 Observe que, se você quiser realizar essas operações em todos os elementos do array com um **valor fixo**, é possível utilizar este valor como um escalar, sem a necessidade de transformá-lo em um array. Isto é possível graças à propriedade de broadcasting.