In [1]:
import numpy as np
np.__version__

'2.3.2'

### Agrupando e dividindo arrays

#### `np.concatenate` / `np.stack` / `np.vstack` / `np.hstack`

Primeiro utilize `np.arange` e `reshape` para criar um array 2D com valores entre 0 e 1, e step igual a 0.1, organizados como uma matriz de 2 linhas e 5 colunas.

In [2]:
array_0 = np.arange(start=0, step=0.1, stop=1).reshape(2, 5)

In [3]:
array_0

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

Agora crie um segundo array com valores entre 1 e 2, e step 0.1, no mesmo formato.

In [4]:
array_1 = np.arange(start=1, step=0.1, stop=2).reshape(2, 5)

In [5]:
array_1

array([[1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

Utilize `np.concatenate` para concatenar os dois arrays ao longo das linhas, ou seja, do eixo 0.

In [6]:
np.concatenate([array_0, array_1])

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

👆 Observe que o novo array tem agora 4 linhas e 5 colunas.

Utilize `np.vstack` para empilhar os dois arrays verticalmente, e observe que o resultado é o mesmo que aquele de `np.concatenate` com `axis=0`.

In [7]:
np.vstack(tup=[array_0, array_1])

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

Utilize `np.stack` para empilhar os dois arrays no eixo 0, mas observe que neste caso, uma nova dimensão é criada.

In [12]:
array_stacked = np.stack(arrays=[array_0, array_1])
array_stacked

array([[[0. , 0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8, 0.9]],

       [[1. , 1.1, 1.2, 1.3, 1.4],
        [1.5, 1.6, 1.7, 1.8, 1.9]]])

Agora repita o procedimento em relação ao eixo 1. Neste caso, você deve usar `np.hstack`.

In [9]:
np.hstack(tup=[array_0, array_1])

array([[0. , 0.1, 0.2, 0.3, 0.4, 1. , 1.1, 1.2, 1.3, 1.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 1.5, 1.6, 1.7, 1.8, 1.9]])

In [10]:
np.hstack(tup=[array_0, array_1])

array([[0. , 0.1, 0.2, 0.3, 0.4, 1. , 1.1, 1.2, 1.3, 1.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 1.5, 1.6, 1.7, 1.8, 1.9]])

In [15]:
np.stack(arrays=[array_1, array_0])

array([[[1. , 1.1, 1.2, 1.3, 1.4],
        [1.5, 1.6, 1.7, 1.8, 1.9]],

       [[0. , 0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8, 0.9]]])

### Adicionando eixos

#### `np.expand_dims`

Adicione uma dimensão no eixo 0 de `array_0`.

Exiba o array resultante e seu `shape` para observar o efeito que esta operação teve.

In [16]:
array_0_ed_0 = np.expand_dims(a=array_0, axis=0)

In [17]:
array_0_ed_0

array([[[0. , 0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8, 0.9]]])

In [18]:
array_0_ed_0.shape

(1, 2, 5)

Agora repita para o eixo 1.

In [22]:
array_0_ed_1 = np.expand_dims(a=array_0, axis=1)

In [23]:
array_0_ed_1

array([[[0. , 0.1, 0.2, 0.3, 0.4]],

       [[0.5, 0.6, 0.7, 0.8, 0.9]]])

In [24]:
array_0_ed_1.shape

(2, 1, 5)

Repita para o eixo 2.

In [25]:
array_0_ed_2 = np.expand_dims(a=array_0, axis=2)

In [26]:
array_0_ed_2

array([[[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4]],

       [[0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9]]])

In [27]:
array_0_ed_2.shape

(2, 5, 1)

### Rearranjando elementos

#### `np.flip`

Inverta `array_0` inteiro, exibindo o resultado para visualizar a alteração.

In [28]:
np.flip(array_0)

array([[0.9, 0.8, 0.7, 0.6, 0.5],
       [0.4, 0.3, 0.2, 0.1, 0. ]])

👆 As linhas e as colunas foram invertidas.

Inverta `array_0` somente no eixo 0.

In [29]:
np.flip(array_0, axis=0)

array([[0.5, 0.6, 0.7, 0.8, 0.9],
       [0. , 0.1, 0.2, 0.3, 0.4]])

👆 Somente as linhas foram invertidas.

Inverta `array_0` somente no eixo 1.

In [30]:
np.flip(array_0, axis=1)

array([[0.4, 0.3, 0.2, 0.1, 0. ],
       [0.9, 0.8, 0.7, 0.6, 0.5]])

👆 Somente as colunas foram invertidas.

#### `np.resize`

Redimensione `array_0` para o formato linearizado com 8 elementos.

In [31]:
np.resize(a=array_0, new_shape=8)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])

👆 Como o novo tamanho é menor que o anterior, o array original é truncado.

Redimensione `array_0` para o formato linearizado com 15 elementos.

In [32]:
np.resize(a=array_0, new_shape=15)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0. , 0.1, 0.2,
       0.3, 0.4])

👆 Como o novo tamanho é maior que o anterior, o array original é repetido até o novo tamanho.

Redimensione `array_0` para conter 3 linhas e 6 colunas.

In [33]:
np.resize(a=array_0, new_shape=(3, 6))

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 0. , 0.1],
       [0.2, 0.3, 0.4, 0.5, 0.6, 0.7]])

👆 Lembre-se que o array é primeiro linearizado, depois truncado ou completado até o novo tamanho, depois o formato é ajustado.

### Adicionando ou removendo elementos

#### `np.insert`

Insira uma nova coluna (eixo 1) em `array_0` na posição 2 com o valor 9.

In [35]:
np.insert(arr=array_0, obj=2, values=9, axis=1)

array([[0. , 0.1, 9. , 0.2, 0.3, 0.4],
       [0.5, 0.6, 9. , 0.7, 0.8, 0.9]])

Repita a inserção, mas com os valores 8 e 9.

In [36]:
np.insert(arr=array_0, obj=2, values=[8, 9], axis=1)

array([[0. , 0.1, 8. , 0.2, 0.3, 0.4],
       [0.5, 0.6, 9. , 0.7, 0.8, 0.9]])

Agora insira uma linha (eixo 0) em `array_0` na posição 0 com o valor 9.

In [38]:
np.insert(arr=array_0, obj=0, values=9, axis=0)

array([[9. , 9. , 9. , 9. , 9. ],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

#### `np.delete`

Delete a coluna 2 de `array_0`.

In [39]:
np.delete(arr=array_0, obj=2, axis=1)

array([[0. , 0.1, 0.3, 0.4],
       [0.5, 0.6, 0.8, 0.9]])

Delete a linha 1 de `array_1`.

In [41]:
np.delete(arr=array_0, obj=0, axis=0)

array([[0.5, 0.6, 0.7, 0.8, 0.9]])

#### `np.append`

Adicione `array_1` ao final de `array_0`, no eixo 0.

In [45]:
np.append(arr=array_0, values=array_1, axis=0)

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

👆 O resultado é o mesmo de `np.concatenate` com `axis=0`.

Adicione `array_1` ao final de `array_0`, no eixo 1.

In [46]:
np.append(arr=array_0, values=array_1, axis=1)

array([[0. , 0.1, 0.2, 0.3, 0.4, 1. , 1.1, 1.2, 1.3, 1.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 1.5, 1.6, 1.7, 1.8, 1.9]])

👆 O resultado é o mesmo de `np.concatenate` com `axis=1`.

#### `np.tile`

Utilize `np.tile` para repetir `array_0`, 2 vezes no eixo 0, e 4 vezes no eixo 1.

In [47]:
np.tile(A=array_0, reps=(2, 4))

array([[0. , 0.1, 0.2, 0.3, 0.4, 0. , 0.1, 0.2, 0.3, 0.4, 0. , 0.1, 0.2,
        0.3, 0.4, 0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 0.5, 0.6, 0.7, 0.8, 0.9, 0.5, 0.6, 0.7,
        0.8, 0.9, 0.5, 0.6, 0.7, 0.8, 0.9],
       [0. , 0.1, 0.2, 0.3, 0.4, 0. , 0.1, 0.2, 0.3, 0.4, 0. , 0.1, 0.2,
        0.3, 0.4, 0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 0.5, 0.6, 0.7, 0.8, 0.9, 0.5, 0.6, 0.7,
        0.8, 0.9, 0.5, 0.6, 0.7, 0.8, 0.9]])

E se você quiser repetir `array_0` somente 3 vezes no eixo 0?

In [50]:
np.tile(A=array_0, reps=(3, 1))

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

#### `np.pad`

Preencha `array_1` com 3 valores antes e 4 valores depois. O valor deve ser a constante 0.

In [6]:
np.pad(array=array_1, pad_width=(3, 4), mode='constant', constant_values=(0))

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. , 1.1, 1.2, 1.3, 1.4, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1.5, 1.6, 1.7, 1.8, 1.9, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

👆 Foram adicionadas 3 linhas e 3 colunas "antes" de `array_1`, e 4 linhas/4 colunas "depois".

Repita, mas preenchendo com os valores da borda ("edge").

In [8]:
np.pad(array=array_1, pad_width=(3, 4), mode='edge')

array([[1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9]])

Repita com o valor mínimo.

In [9]:
np.pad(array=array_1, pad_width=(3, 4), mode='minimum')

array([[1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.5, 1.5, 1.5, 1.5],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ]])

Repita com o valor máximo.

In [10]:
np.pad(array=array_1, pad_width=(3, 4), mode='maximum')

array([[1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.4, 1.4, 1.4, 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9]])

#### `np.trim_zeros`

Esta função só funciona com arrays 1D.

Primeiro crie um array 1D com valores entre 1 e 5, e step = 0.5. Utilize `np.arange` para isso.

In [11]:
array = np.arange(start=1, step=0.5, stop=5)

In [12]:
array

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Agora utilize `np.pad` para adicionar 6 valores 0 à esquerda e 4 valores 0 à direita de `array`.

In [15]:
array_pad = np.pad(array=array, pad_width=(6, 4), mode='constant', constant_values=(0))

In [16]:
array_pad

array([0. , 0. , 0. , 0. , 0. , 0. , 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ,
       4.5, 0. , 0. , 0. , 0. ])

Aplique `np.trim` em `array_pad` para retirar os valores 0 das extremidades, assim recuperando `array`.

In [17]:
array_trim = np.trim_zeros(filt=array_pad)

In [18]:
array_trim

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Repita a operação utilizando o parâmetro `trim` para remover somente os valores 0 da "frente" (`f`) de `array_pad`.

In [19]:
array_trim = np.trim_zeros(filt=array_pad, trim='f')

In [20]:
array_trim

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 0. , 0. , 0. , 0. ])

#### `np.unique`

Vamos começar criando um array grande de números inteiros aleatórios, onde certamente vão existir repetições.

Primeiro, instancie um gerador de números aleatórios com `np.random.default_rng`. Configure a `seed` para o valor 75.

In [21]:
rng = np.random.default_rng(seed=75)

Agora gere um array com 200 valores inteiros aleatórios no intervalo [50, 75).

In [24]:
array_unique = rng.integers(low=50, high=75, size=200)

In [25]:
array_unique

array([66, 55, 55, 53, 73, 66, 58, 67, 68, 73, 58, 68, 69, 73, 69, 73, 67,
       71, 50, 50, 66, 60, 54, 70, 63, 50, 63, 53, 67, 74, 65, 74, 51, 70,
       50, 71, 60, 60, 73, 66, 59, 70, 62, 74, 71, 55, 53, 58, 67, 60, 50,
       54, 69, 74, 68, 72, 69, 56, 67, 52, 51, 70, 68, 54, 71, 54, 57, 69,
       66, 69, 62, 61, 64, 74, 73, 70, 63, 64, 55, 50, 71, 63, 67, 60, 56,
       61, 66, 61, 70, 56, 67, 53, 68, 61, 69, 69, 58, 68, 65, 58, 67, 67,
       57, 69, 63, 68, 66, 70, 68, 74, 60, 62, 50, 66, 72, 66, 66, 55, 73,
       51, 69, 58, 72, 67, 57, 67, 52, 72, 61, 55, 65, 73, 50, 66, 63, 69,
       59, 50, 69, 51, 72, 67, 64, 58, 71, 64, 52, 67, 60, 60, 62, 63, 61,
       67, 61, 57, 60, 57, 73, 62, 74, 71, 57, 62, 58, 59, 72, 71, 62, 67,
       52, 68, 74, 55, 61, 67, 62, 61, 55, 54, 57, 63, 51, 55, 72, 55, 70,
       52, 55, 51, 52, 51, 66, 74, 62, 53, 50, 70, 50, 52])

Com uma única chamada de `np.unique`, recupere:
- os valores únicos
- os índices onde cada valor aparece pela primeira vez (parâmetro `return_index`)
- os índices que podem ser utilizados para reconstruir o array original a partir dos valores únicos (parâmetro `return_inverse`)
- a contagem dos valores únicos (parâmetro `return_counts`)

In [26]:
unique_values, indices_first, indices_redo, counts = np.unique(ar=array_unique, return_index=True, return_inverse=True, return_counts=True)

In [27]:
unique_values

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74])

In [28]:
indices_first

array([18, 32, 59,  3, 22,  1, 57, 66,  6, 40, 21, 71, 42, 24, 72, 30,  0,
        7,  8, 12, 23, 17, 55,  4, 29])

In [29]:
indices_redo

array([16,  5,  5,  3, 23, 16,  8, 17, 18, 23,  8, 18, 19, 23, 19, 23, 17,
       21,  0,  0, 16, 10,  4, 20, 13,  0, 13,  3, 17, 24, 15, 24,  1, 20,
        0, 21, 10, 10, 23, 16,  9, 20, 12, 24, 21,  5,  3,  8, 17, 10,  0,
        4, 19, 24, 18, 22, 19,  6, 17,  2,  1, 20, 18,  4, 21,  4,  7, 19,
       16, 19, 12, 11, 14, 24, 23, 20, 13, 14,  5,  0, 21, 13, 17, 10,  6,
       11, 16, 11, 20,  6, 17,  3, 18, 11, 19, 19,  8, 18, 15,  8, 17, 17,
        7, 19, 13, 18, 16, 20, 18, 24, 10, 12,  0, 16, 22, 16, 16,  5, 23,
        1, 19,  8, 22, 17,  7, 17,  2, 22, 11,  5, 15, 23,  0, 16, 13, 19,
        9,  0, 19,  1, 22, 17, 14,  8, 21, 14,  2, 17, 10, 10, 12, 13, 11,
       17, 11,  7, 10,  7, 23, 12, 24, 21,  7, 12,  8,  9, 22, 21, 12, 17,
        2, 18, 24,  5, 11, 17, 12, 11,  5,  4,  7, 13,  1,  5, 22,  5, 20,
        2,  5,  1,  2,  1, 16, 24, 12,  3,  0, 20,  0,  2])

In [30]:
counts

array([11,  7,  7,  5,  5, 11,  3,  7,  8,  3,  9,  9,  9,  8,  4,  3, 12,
       16,  9, 12,  9,  8,  7,  9,  9])

Utilize `unique_values` e `indices_redo` para reconstruir o array original.

In [31]:
unique_values[indices_redo]

array([66, 55, 55, 53, 73, 66, 58, 67, 68, 73, 58, 68, 69, 73, 69, 73, 67,
       71, 50, 50, 66, 60, 54, 70, 63, 50, 63, 53, 67, 74, 65, 74, 51, 70,
       50, 71, 60, 60, 73, 66, 59, 70, 62, 74, 71, 55, 53, 58, 67, 60, 50,
       54, 69, 74, 68, 72, 69, 56, 67, 52, 51, 70, 68, 54, 71, 54, 57, 69,
       66, 69, 62, 61, 64, 74, 73, 70, 63, 64, 55, 50, 71, 63, 67, 60, 56,
       61, 66, 61, 70, 56, 67, 53, 68, 61, 69, 69, 58, 68, 65, 58, 67, 67,
       57, 69, 63, 68, 66, 70, 68, 74, 60, 62, 50, 66, 72, 66, 66, 55, 73,
       51, 69, 58, 72, 67, 57, 67, 52, 72, 61, 55, 65, 73, 50, 66, 63, 69,
       59, 50, 69, 51, 72, 67, 64, 58, 71, 64, 52, 67, 60, 60, 62, 63, 61,
       67, 61, 57, 60, 57, 73, 62, 74, 71, 57, 62, 58, 59, 72, 71, 62, 67,
       52, 68, 74, 55, 61, 67, 62, 61, 55, 54, 57, 63, 51, 55, 72, 55, 70,
       52, 55, 51, 52, 51, 66, 74, 62, 53, 50, 70, 50, 52])