# **Funções de Manipulação**

In [1]:
import numpy as np

## Agrupando e dividindo arrays

In [2]:
array_1d = np.arange(0, 10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array_2d_0 = np.arange(0, 18).reshape(3, 6)
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [4]:
array_2d_1 = np.arange(18, 36).reshape(3, 6)
array_2d_1

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### np.concatenate

In [5]:
np.concatenate([array_2d_0, array_2d_1])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
np.concatenate([array_2d_0, array_2d_1], axis=1)

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

### np.stack

In [7]:
array_stacked = np.stack(arrays=[array_2d_0, array_2d_1])
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [8]:
array_stacked.shape

(2, 3, 6)

In [9]:
array_stacked = np.stack(arrays=[array_2d_0, array_2d_1], axis=1)
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [18, 19, 20, 21, 22, 23]],

       [[ 6,  7,  8,  9, 10, 11],
        [24, 25, 26, 27, 28, 29]],

       [[12, 13, 14, 15, 16, 17],
        [30, 31, 32, 33, 34, 35]]])

In [10]:
array_stacked.shape

(3, 2, 6)

In [11]:
array_stacked = np.stack(arrays=[array_2d_0, array_2d_1], axis=-1)
array_stacked

array([[[ 0, 18],
        [ 1, 19],
        [ 2, 20],
        [ 3, 21],
        [ 4, 22],
        [ 5, 23]],

       [[ 6, 24],
        [ 7, 25],
        [ 8, 26],
        [ 9, 27],
        [10, 28],
        [11, 29]],

       [[12, 30],
        [13, 31],
        [14, 32],
        [15, 33],
        [16, 34],
        [17, 35]]])

In [12]:
array_stacked.shape

(3, 6, 2)

### np.vsstack e np.hstack

In [13]:
np.vstack(tup=[array_2d_0, array_2d_1])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [14]:
np.hstack(tup=[array_2d_0, array_2d_1])

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

### np.split

In [15]:
np.split(ary=array_1d, indices_or_sections=2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [16]:
np.split(ary=array_2d_0, indices_or_sections=3, axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

### np.vsplit e np.hsplit

In [17]:
np.vsplit(ary=array_2d_0, indices_or_sections=3)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [18]:
np.hsplit(ary=array_2d_0, indices_or_sections=3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

## Adicionando eixos

### np.expand_dims

In [19]:
array_2d_0.ndim

2

In [20]:
array_2d_0.shape

(3, 6)

In [21]:
new_array_2d_0 = np.expand_dims(a=array_2d_0, axis=0)
new_array_2d_0

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]])

In [22]:
new_array_2d_0.ndim, new_array_2d_0.shape

(3, (1, 3, 6))

In [23]:
np.squeeze(new_array_2d_0).shape

(3, 6)

In [24]:
new_array_2d_0 = np.expand_dims(a=array_2d_0, axis=1)
new_array_2d_0

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]]])

In [25]:
new_array_2d_0.ndim, new_array_2d_0.shape

(3, (3, 1, 6))

In [26]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [27]:
array_2d_0[np.newaxis, :], array_2d_0[np.newaxis, :].shape

(array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]]]),
 (1, 3, 6))

In [28]:
array_2d_0[:, np.newaxis, :], array_2d_0[:, np.newaxis, :].shape

(array([[[ 0,  1,  2,  3,  4,  5]],
 
        [[ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17]]]),
 (3, 1, 6))

In [29]:
array_2d_0.reshape(3, 1, 6)

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]]])

## Rearranjando elementos

### np.flip

In [30]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.flip(array_1d)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
array_1d[:: -1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [33]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [34]:
np.flip(array_2d_0)

array([[17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [35]:
np.flip(array_2d_0, axis=0)

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [36]:
np.flip(array_2d_0, axis=1)

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12]])

### np.resize

In [37]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [38]:
np.resize(a=array_2d_0, new_shape=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.resize(a=array_2d_0, new_shape=(4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [40]:
np.resize(a=array_2d_0, new_shape=(8, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [41]:
np.resize(a=array_2d_0, new_shape=(2, 5, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

## Adicionando ou removendo elemento

### np.insert

In [42]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.insert(arr=array_1d, obj=4, values=1)

array([0, 1, 2, 3, 1, 4, 5, 6, 7, 8, 9])

In [44]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [45]:
np.insert(arr=array_2d_0, obj=1, values=-1, axis=1)

array([[ 0, -1,  1,  2,  3,  4,  5],
       [ 6, -1,  7,  8,  9, 10, 11],
       [12, -1, 13, 14, 15, 16, 17]])

In [46]:
np.insert(arr=array_2d_0, obj=1, values=[-1, -2, -3], axis=1)

array([[ 0, -1,  1,  2,  3,  4,  5],
       [ 6, -2,  7,  8,  9, 10, 11],
       [12, -3, 13, 14, 15, 16, 17]])

### np.delete

In [47]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.delete(arr=array_1d, obj=4)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [49]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [50]:
np.delete(arr=array_2d_0, obj=1, axis=1)

array([[ 0,  2,  3,  4,  5],
       [ 6,  8,  9, 10, 11],
       [12, 14, 15, 16, 17]])

### np.append

In [51]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.append(arr=array_1d, values=[0, 1, 2])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [53]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [54]:
np.append(arr=array_2d_0, values=[[0, 1, 2, 3, 4, 5]], axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5]])

In [55]:
np.append(arr=array_2d_0, values=[[0], [6], [12]], axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0],
       [ 6,  7,  8,  9, 10, 11,  6],
       [12, 13, 14, 15, 16, 17, 12]])

### np.tile

In [56]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.tile(A=array_1d, reps=2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.tile(A=array_1d, reps=(2,2))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
np.tile(A=array_2d_0, reps=(3,2))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17]])

### np.pad

In [60]:
array_pad_1d = np.array([1, 2, 3])

In [61]:
np.pad(array=array_pad_1d, pad_width=(1, 2), mode='constant', constant_values=(10, 20))

array([10,  1,  2,  3, 20, 20])

In [62]:
np.pad(array=array_pad_1d, pad_width=(1, 2), mode='edge')

array([1, 1, 2, 3, 3, 3])

In [63]:
np.pad(array=array_pad_1d, pad_width=(1, 2), mode='minimum')

array([1, 1, 2, 3, 1, 1])

In [64]:
np.pad(array=array_pad_1d, pad_width=(1, 2), mode='maximum')

array([3, 1, 2, 3, 3, 3])

In [65]:
np.pad(array=array_pad_1d, pad_width=(1, 2), mode='mean')

array([2, 1, 2, 3, 2, 2])

In [66]:
array_pad_2d = np.array([
    [1, 2],
    [3, 4]
])

In [67]:
np.pad(array=array_pad_2d, pad_width=(1,2), mode='reflect')

array([[4, 3, 4, 3, 4],
       [2, 1, 2, 1, 2],
       [4, 3, 4, 3, 4],
       [2, 1, 2, 1, 2],
       [4, 3, 4, 3, 4]])

### np.trim_zeros

In [68]:
array_with_zeros = np.array([0, 0, 1, 2, 3, 4, 5, 0, 0, 0])
array_with_zeros

array([0, 0, 1, 2, 3, 4, 5, 0, 0, 0])

In [69]:
np.trim_zeros(filt=array_with_zeros)

array([1, 2, 3, 4, 5])

In [70]:
np.trim_zeros(filt=array_with_zeros, trim='f')

array([1, 2, 3, 4, 5, 0, 0, 0])

In [71]:
np.trim_zeros(filt=array_with_zeros, trim='b')

array([0, 0, 1, 2, 3, 4, 5])

## Obtendo valores únicos

### np.unique

In [72]:
array_unique = np.array([7, 8, 8, 6, 8, 7, 7])

In [73]:
np.unique(ar=array_unique)

array([6, 7, 8])

In [74]:
np.unique(ar=array_unique, return_index=True)

(array([6, 7, 8]), array([3, 0, 1]))

In [75]:
unique_values, indices = np.unique(ar=array_unique, return_inverse=True)
unique_values, indices

(array([6, 7, 8]), array([1, 2, 2, 0, 2, 1, 1]))

In [76]:
unique_values

array([6, 7, 8])

In [77]:
unique_values[indices]

array([7, 8, 8, 6, 8, 7, 7])

In [78]:
np.unique(ar=array_unique, return_counts=True)

(array([6, 7, 8]), array([1, 3, 3]))

In [79]:
array_unique_2d = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [0, 1, 2]
])

In [80]:
np.unique(ar=array_unique_2d, return_counts=True)

(array([0, 1, 2, 3, 4, 5]), array([2, 2, 2, 1, 1, 1]))

In [81]:
np.unique(ar=array_unique_2d, return_counts=True, axis=0)

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([2, 1]))