# **Funções de Manipulação**

In [1]:
import numpy as np

## Agrupando e dividindo arrays

In [2]:
array_1d = np.arange(0, 10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array_2d_0 = np.arange(0, 18).reshape(3, 6)
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [4]:
array_2d_1 = np.arange(18, 36).reshape(3, 6)
array_2d_1

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### np.concatenate

In [5]:
np.concatenate([array_2d_0, array_2d_1])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
np.concatenate([array_2d_0, array_2d_1], axis=1)

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

### np.stack

In [7]:
array_stacked = np.stack(arrays=[array_2d_0, array_2d_1])
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [8]:
array_stacked.shape

(2, 3, 6)

In [9]:
array_stacked = np.stack(arrays=[array_2d_0, array_2d_1], axis=1)
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [18, 19, 20, 21, 22, 23]],

       [[ 6,  7,  8,  9, 10, 11],
        [24, 25, 26, 27, 28, 29]],

       [[12, 13, 14, 15, 16, 17],
        [30, 31, 32, 33, 34, 35]]])

In [10]:
array_stacked.shape

(3, 2, 6)

In [11]:
array_stacked = np.stack(arrays=[array_2d_0, array_2d_1], axis=-1)
array_stacked

array([[[ 0, 18],
        [ 1, 19],
        [ 2, 20],
        [ 3, 21],
        [ 4, 22],
        [ 5, 23]],

       [[ 6, 24],
        [ 7, 25],
        [ 8, 26],
        [ 9, 27],
        [10, 28],
        [11, 29]],

       [[12, 30],
        [13, 31],
        [14, 32],
        [15, 33],
        [16, 34],
        [17, 35]]])

In [12]:
array_stacked.shape

(3, 6, 2)

### np.vsstack e np.hstack

In [13]:
np.vstack(tup=[array_2d_0, array_2d_1])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [14]:
np.hstack(tup=[array_2d_0, array_2d_1])

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

### np.split

In [15]:
np.split(ary=array_1d, indices_or_sections=2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [16]:
np.split(ary=array_2d_0, indices_or_sections=3, axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

### np.vsplit e np.hsplit

In [17]:
np.vsplit(ary=array_2d_0, indices_or_sections=3)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [18]:
np.hsplit(ary=array_2d_0, indices_or_sections=3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]